{{- if .Values.secret.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sample.releaseName" . }}
  {{- with .Values.secret.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secret.external.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: {{ include "sample.releaseName" . }}
    creationPolicy: Owner
  dataFrom:
  {{- if .Values.secret.external.additional }}
  {{- range .Values.secret.external.additional }}
  - extract:
      key: {{ . }}  
  {{- end }}
  {{- end }}
  {{- if .Values.secret.external.default.enabled }}
  - extract:
      key: {{ include "sample.releaseName" . }}-{{ .Values.project.env }}
  {{- end }}
  {{- if .Values.secret.external.database.enabled }}
  - extract:
      key: {{ .Values.secret.external.database.name }}
  {{- end }}
{{- end }}
