{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sample.releaseName" . }}
{{- if .Values.persistentVolumeClaim.spec }}
spec:
  {{- toYaml .Values.persistentVolumeClaim.spec | nindent 2 }}
{{- end }}
{{- end }}
