{{- if or .Values.serviceAccount.enabled (and .Values.istio.enabled .Values.istio.serviceAccount.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample.releaseName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
